### ISSUE TITLE
Add CI workflow

### ISSUE THREAD

**Issue by etpinard** [plotly/DashBase.jl#3]

**Comment by sjkelly** [comment]
What does Plotly use for CI? I don't see many repos with GHA enabled.

**Comment by etpinard** [comment]
I think most Plotly repos use CircleCI, but for pure Julia unit tests, that's probably an overkill.

Something like https://github.com/plotly/Dash.jl/blob/dev/.github/workflows/jl_test.yml would be :ok_hand:
